services:
  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - VLLM_API_BASE=http://llm:8001/v1
      - MODEL_NAME=facebook/opt-125m
    volumes:
      - ./llm:/workspace

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - llm
    environment:
      - VLLM_API_BASE=http://llm:8001/v1
    volumes:
      - ./mcp_server:/workspace

  mcp_client:
    build:
      context: ./mcp_client
      dockerfile: Dockerfile
    depends_on:
      - mcp_server
    stdin_open: true
    tty: true
    environment:
      - VLLM_API_BASE=http://llm:8001/v1
    volumes:
      - ./mcp_client:/workspace
